import buffer.BufferManager;
import catalog.IndexEntry;
import catalog.TableEntry;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import storage.BTreeManager;
import storage.GenericPage;
import storage.GenericRecord;
import storage.K;
import storage.RawPage;
import storage.RecordId;
import trace.QueryTrace;
import trace.QueryTraceJson;
import util.RecordUtils;

/** Builds the committed web demo trace from a deterministic miniature database. */
public final class DemoTraceExport {
    public static final String DEFAULT_OUTPUT = "web/public/data/query-trace-default.json";
    public static final String DEFAULT_START = "M";
    public static final String DEFAULT_END = "Mz";
    public static final int DEFAULT_BUFFER_SIZE = 5;
    public static final boolean DEFAULT_INDEXED = true;

    private static final String MARKER_FILE = ".demo-trace-fixtures.marker";

    private DemoTraceExport() {}

    public static void main(String[] args) throws Exception {
        Path output = args.length == 0 ? Path.of(DEFAULT_OUTPUT) : Path.of(args[0]);
        writeFixtureFiles();
        QueryTrace trace = RunQuery.capture(DEFAULT_START, DEFAULT_END, DEFAULT_BUFFER_SIZE, DEFAULT_INDEXED);
        QueryTraceJson.write(trace, output);
        System.out.println("Wrote " + output + " with " + trace.events().size() + " trace events.");
    }

    static void writeFixtureFiles() throws IOException {
        guardAgainstForeignFile(RunQuery.MOVIES_DB);
        guardAgainstForeignFile(RunQuery.WORKEDON_DB);
        guardAgainstForeignFile(RunQuery.PEOPLE_DB);
        guardAgainstForeignFile(RunQuery.TITLE_IDX);

        resetGeneratedFile(RunQuery.MOVIES_DB);
        resetGeneratedFile(RunQuery.WORKEDON_DB);
        resetGeneratedFile(RunQuery.PEOPLE_DB);
        resetGeneratedFile(RunQuery.TITLE_IDX);
        Files.deleteIfExists(Path.of(MARKER_FILE));
        Files.createFile(Path.of(MARKER_FILE));

        BufferManager bm = new BufferManager(12);
        bm.register(new TableEntry(RunQuery.MOVIES_DB, RunQuery.MOVIES_SCHEMA));
        bm.register(new TableEntry(RunQuery.WORKEDON_DB, RunQuery.WORKEDON_SCHEMA));
        bm.register(new TableEntry(RunQuery.PEOPLE_DB, RunQuery.PEOPLE_SCHEMA));
        bm.register(new IndexEntry(RunQuery.TITLE_IDX, RunQuery.MOVIES_SCHEMA.get("title")));

        List<MovieIndexEntry> movieIndex = writeMovies(bm);
        writeWorkedOn(bm);
        writePeople(bm);
        writeTitleIndex(bm, movieIndex);
        bm.force();
    }

    static void cleanupGeneratedFiles() throws IOException {
        Files.deleteIfExists(Path.of(RunQuery.MOVIES_DB));
        Files.deleteIfExists(Path.of(RunQuery.WORKEDON_DB));
        Files.deleteIfExists(Path.of(RunQuery.PEOPLE_DB));
        Files.deleteIfExists(Path.of(RunQuery.TITLE_IDX));
        Files.deleteIfExists(Path.of(RunQuery.QUERY_RESULTS));
        Files.deleteIfExists(Path.of(MARKER_FILE));
    }

    /**
     * Refuses to touch {@code fileId} if it already exists but wasn't left behind by a
     * prior run of this exporter, so a developer's real dataset in the working directory
     * is never silently deleted.
     */
    private static void guardAgainstForeignFile(String fileId) throws IOException {
        if (Files.exists(Path.of(fileId)) && !Files.exists(Path.of(MARKER_FILE))) {
            throw new IllegalStateException(
                    "Refusing to overwrite " + fileId + ": it already exists and was not generated by "
                            + DemoTraceExport.class.getSimpleName()
                            + ". Move or remove it before running the demo trace export.");
        }
    }

    private static List<MovieIndexEntry> writeMovies(BufferManager bm) throws IOException {
        List<MovieIndexEntry> indexEntries = new ArrayList<>();
        RawPage raw = bm.createPage(RunQuery.MOVIES_DB, null);
        GenericPage page = new GenericPage(raw, RunQuery.MOVIES_SCHEMA);
        for (MovieRow row : List.of(
                new MovieRow("tt0000001", "Alpha"),
                new MovieRow("tt0000002", "Moonrise"),
                new MovieRow("tt0000003", "Mosaic"),
                new MovieRow("tt0000004", "Murmur"),
                new MovieRow("tt0000005", "Zed"))) {
            GenericRecord record = GenericRecord.create(RunQuery.MOVIES_SCHEMA)
                    .set("movieId", RecordUtils.toFixedBytes(row.movieId(), RunQuery.MOVIES_SCHEMA.get("movieId")))
                    .set("title", RecordUtils.toFixedBytes(row.title(), RunQuery.MOVIES_SCHEMA.get("title")));
            int slotId = page.insertRecord(record);
            if (slotId < 0) {
                throw new IllegalStateException("demo movie page unexpectedly filled");
            }
            indexEntries.add(new MovieIndexEntry(row.title(), new RecordId(raw.getPid(), slotId)));
        }
        bm.markDirty(RunQuery.MOVIES_DB, raw.getPid());
        bm.unpinPage(RunQuery.MOVIES_DB, raw.getPid());
        return indexEntries;
    }

    private static void writeWorkedOn(BufferManager bm) throws IOException {
        List<WorkedOnRow> rows = List.of(
                new WorkedOnRow("tt0000002", "nm0000001", "director"),
                new WorkedOnRow("tt0000003", "nm0000002", "director"),
                new WorkedOnRow("tt0000004", "nm0000003", "director"),
                new WorkedOnRow("tt0000004", "nm0000004", "actor"),
                new WorkedOnRow("tt0000005", "nm0000005", "director"));
        RawPage raw = bm.createPage(RunQuery.WORKEDON_DB, null);
        GenericPage page = new GenericPage(raw, RunQuery.WORKEDON_SCHEMA);
        for (WorkedOnRow row : rows) {
            GenericRecord record = GenericRecord.create(RunQuery.WORKEDON_SCHEMA)
                    .set("movieId", RecordUtils.toFixedBytes(row.movieId(), RunQuery.WORKEDON_SCHEMA.get("movieId")))
                    .set("personId", RecordUtils.toFixedBytes(row.personId(), RunQuery.WORKEDON_SCHEMA.get("personId")))
                    .set("category", RecordUtils.toFixedBytes(row.category(), RunQuery.WORKEDON_SCHEMA.get("category")));
            if (page.insertRecord(record) < 0) {
                throw new IllegalStateException("demo workedon page unexpectedly filled");
            }
        }
        bm.markDirty(RunQuery.WORKEDON_DB, raw.getPid());
        bm.unpinPage(RunQuery.WORKEDON_DB, raw.getPid());
    }

    private static void writePeople(BufferManager bm) throws IOException {
        List<PersonRow> rows = List.of(
                new PersonRow("nm0000001", "Mira Stone"),
                new PersonRow("nm0000002", "Noah Vale"),
                new PersonRow("nm0000003", "Oren Pike"),
                new PersonRow("nm0000004", "Pia Lane"),
                new PersonRow("nm0000005", "Quinn Ray"));
        RawPage raw = bm.createPage(RunQuery.PEOPLE_DB, null);
        GenericPage page = new GenericPage(raw, RunQuery.PEOPLE_SCHEMA);
        for (PersonRow row : rows) {
            GenericRecord record = GenericRecord.create(RunQuery.PEOPLE_SCHEMA)
                    .set("personId", RecordUtils.toFixedBytes(row.personId(), RunQuery.PEOPLE_SCHEMA.get("personId")))
                    .set("name", RecordUtils.toFixedBytes(row.name(), RunQuery.PEOPLE_SCHEMA.get("name")));
            if (page.insertRecord(record) < 0) {
                throw new IllegalStateException("demo people page unexpectedly filled");
            }
        }
        bm.markDirty(RunQuery.PEOPLE_DB, raw.getPid());
        bm.unpinPage(RunQuery.PEOPLE_DB, raw.getPid());
    }

    private static void writeTitleIndex(BufferManager bm, List<MovieIndexEntry> entries) throws IOException {
        BTreeManager index = new BTreeManager(
                RunQuery.BTREE_DEGREE,
                RunQuery.TITLE_IDX,
                bm,
                RunQuery.MOVIES_SCHEMA.get("title"));
        for (MovieIndexEntry entry : entries) {
            index.insert(
                    new K(RecordUtils.toFixedBytes(entry.title(), RunQuery.MOVIES_SCHEMA.get("title"))),
                    entry.recordId());
        }
    }

    private static void resetGeneratedFile(String fileId) throws IOException {
        Path path = Path.of(fileId);
        Files.deleteIfExists(path);
        Files.createFile(path);
    }

    private record MovieRow(String movieId, String title) {}

    private record WorkedOnRow(String movieId, String personId, String category) {}

    private record PersonRow(String personId, String name) {}

    private record MovieIndexEntry(String title, RecordId recordId) {}
}
